name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run linting
      run: |
        set -e
        poetry run black --check --diff --color .
        poetry run isort --check-only .
        # poetry run pylint .

    - name: Run e2e tests
      run: |
        set -e
        pip install poetry
        poetry env use 3.10
        poetry install
        poetry run pytest tests
